# coding: utf-8

from app import app
from Model import *
db.app=app
db.init_app(app)
db.create_all()


course = Course('SOA', 'SOA')
db.session.add(course)
course = Course('SOC', 'SOC')
db.session.add(course)
db.session.commit()

orgs = [u'哈佛大学（Harvard, MA）',
u'普林斯顿大学（Princeton University）（Princeton, NJ）',
u'耶鲁大学（New Haven, CT）',
u'哥伦比亚大学（New York, NY）',
u'芝加哥大学（Chicago, IL）',
u'麻省理工学院（Cambridge, MA）',
u'斯坦福大学（Stanford, CA）',
u'杜克大学（Duke University）（Durham, NC）',
u'宾夕法尼亚大学（Philadelphia, PA）',
u'美国加州理工学院（Pasadena, CA）',
u'达特茅斯学院（Dartmouth College）（Hanover, NH）',
u'西北大学（Northwestern University）（Evanston, IL）',
u'约翰•霍普金斯大学（马里兰州巴尔的摩市）',
u'华盛顿大学圣路易斯分校（St. Louis, MO）',
u'布朗大学（Brown University）（Providence, RI）',
u'康奈尔大学（Ithaca, NY）',
u'莱斯大学（Rice University）（Houston, TX）',
u'圣母大学（Notre Dame, IN）',
u'范德堡大学（Vanderbilt University）（Nashville, TN）',
u'埃默里大学（Atlanta, GA）',
u'乔治城大学（Georgetown University）（Washington, DC）',
u'美国加州大学伯克利分校（Berkeley, CA）',
u'卡内基梅隆大学（Pittsburgh, PA）',
u'美国加州大学洛杉矶分校（洛杉矶,CA）',
u'美国南加州大学（洛杉矶,CA）',
u'美国弗吉尼亚大学（Charlottesville, VA）',
u'维克森林大学（Winston-Salem, NC）',
u'塔夫茨大学（Medford, MA）',
u'美国密西根大学安娜堡分校（Ann Arbor, MI）',
u'北卡罗来纳大学教堂山分校（Chapel Hill, NC）',
u'波士顿学院（Boston College）（Chestnut Hill, MA）',
u'纽约大学（New York University）（纽约,NY）',
u'布兰代斯大学（马萨诸塞州沃尔瑟姆）',
u'威廉与玛丽学院（弗吉尼亚州威廉斯堡）',
u'罗切斯特大学（纽约州罗切斯特市）',
u'佐治亚理工学院（美国佐治亚州亚特兰大）',
u'凯斯西储大学（俄亥俄州克利夫兰）',
u'美国里海大学（Lehigh University）（宾夕法尼亚州伯利恒）',
u'美国加州大学戴维斯分校（戴维斯,CA）',
u'加州大学圣地亚哥分校（加利福尼亚州拉霍亚）',
u'伦斯勒理工学院（Rensselaer Polytechnic Institute）（纽约州特洛伊）',
u'加州大学圣塔芭芭拉分校（加利福尼亚州圣塔巴巴拉）',
u'美国威斯康星大学麦迪逊分校（麦迪逊,威斯康星）',
u'美国加州大学欧文分校 （加利福尼亚州欧文）',
u'迈阿密大学（佛罗里达州科勒尔盖布尔斯）',
u'宾夕法尼亚州立大学',
u'伊利诺伊大学香槟分校（香槟,IL）',
u'萨斯大学（奥斯汀）',
u'华盛顿大学-西雅图（华盛顿州）',
u'叶史瓦大学（纽约,NY）',
u'波士顿大学（马萨诸塞州波士顿）',
u'乔治华盛顿大学（George Washington University）（华盛顿DC）',
u'美国杜兰大学（新奥尔良,LA）',
u'佩珀代因大学（Pepperdine University）（加利福尼亚州马里布）',
u'佛罗里达大学（佛罗里达州盖恩斯维尔）',
u'东北大学（马萨诸塞州波士顿）',
u'美国俄亥俄州立大学哥伦布分校（俄亥俄州哥伦布市）',
u'福特汉姆大学（Fordham University）（纽约,NY）',
u'南卫理公会大学（德克萨斯州达拉斯）',
u'雪城大学（Syracuse University）（美国纽约州雪城）',
u'马里兰大学学院市分校 （马里兰州College Park）',
u'美国匹兹堡大学（宾夕法尼亚州匹兹堡）',
u'康涅狄格大学（斯托尔斯,CT）',
u'乔治亚大学（雅典,GA）',
u'普渡大学西拉法叶校区 （est Lafayette,IN）',
u'德州农工大学（德克萨斯州College Station）',
u'伍斯特理工学院（马萨诸塞州伍斯特市）',
u'杨百翰大学（普罗沃,UT）',
u'克莱姆森大学（克莱姆森,SC）',
u'州立罗格斯大学（新泽西州Piscataway）',
u'新泽西州立大学新布朗斯威克校（明尼苏达州明尼阿波利斯）',
u'密歇根州立大学（东兰辛,MI）',
u'美国爱荷华大学（爱荷华州爱荷华市）',
u'弗吉尼亚理工大学(弗吉尼亚州布莱克斯堡)',
u'史蒂文斯科技学院(新泽西州Hoboken)',
u'特拉华大学(特拉华州Newark)',
u'美国大学(华盛顿DC)',
u'贝勒大学（Baylor University）(德克萨斯州Waco)',
u'科罗拉多矿业学院(Golden, CO)',
u'美国纽约州立大学环境科学与林业科学学院(美国纽约州雪城)',
u'美国阿拉巴马大学(塔斯卡卢萨,AL)',
u'加州大学圣克鲁兹分校(加利福尼亚州圣克鲁斯)',
u'克拉克大学（Clark University）(马萨诸塞州伍斯特市)',
u'德雷克塞尔大学（Drexel University）(宾夕法尼亚州费城)',
u'印地安那大学伯明顿分校(布卢明顿,IN)',
u'马凯特大学(威斯康星州密尔沃基)',
u'丹佛大学(科罗拉多州丹佛市)',
u'塔尔萨大学(塔尔萨)',
u'奥本大学(奥本大学,AL)',
u'宾厄姆顿大学-纽约州立大学(美国纽约州宾厄姆顿)',
u'迈阿密大学牛津分校(牛津,OH)',
u'华盛顿大学(圣路易斯,密苏里州)',
u'纽约州立大学石溪分校(石溪分校,纽约)',
u'德克萨斯基督教大学(德克萨斯州沃思堡)',
u'圣地亚哥大学(圣地亚哥,加利福尼亚州)',
u'佛蒙特大学(伯灵顿,VT)',
u'佛罗里达州立大学(佛罗里达州塔拉哈西)',
u'科罗拉多大学(科罗拉多州博尔德)',
u'美国马萨诸塞大学 - 阿姆赫斯特(阿默斯特,MA)',
u'密苏里大学(哥伦比亚,MO)', u'剑桥大学(Cambridge)',
u'牛津大学(Oxford)',
u'伦敦政治经济学院(LSE)',
u'圣安德鲁斯大学(St Andrews)',
u'伦敦帝国理工学院(Imperial College)',
u'杜伦大学(Durham)',
u'巴斯大学(Bath)',
u'埃克塞特大学(Exeter)',
u'伦敦大学学院(UCL)',
u'华威大学(Warwick)',
u'约克大学(York)',
u'兰卡斯特大学(Lancaster)',
u'萨里大学(Surrey)',
u'莱斯特大学(Leicester)',
u'布里斯托大学(Bristol)',
u'伯明翰大学(Birmingham)',
u'东安格利亚大学(East Anglia)',
u'谢菲尔德大学(Sheffield)',
u'纽卡斯尔大学(Newcastle)',
u'南安普敦大学(Southampton)',
u'拉夫堡大学(Loughborough)',
u'爱丁堡大学(Edinburgh)',
u'诺丁汉大学(Nottingham)',
u'伦敦大学亚非学院(SOAS)',
u'格拉斯哥大学(Glasgow)',
u'曼切斯特大学(Manchester)',
u'伦敦大学国王学院(Kings College)',
u'伦敦大学皇家霍洛维学院(Royal Holloway)',
u'利兹大学(Leeds)',
u'苏塞克斯大学(Sussex)',
u'卡迪夫大学(Cardiff)',
u'肯特大学(Kent)',
u'雷丁大学(Reading)',
u'利物浦大学(Liverpool)',
u'伦敦大学玛丽女王学院(Queen Mary)',
u'赫瑞-瓦特大学(Heriot-Watt)',
u'埃塞克斯大学(Essex)',
u'阿伯丁大学(Aberdeen)',
u'白金汉大学(Buckingham)',
u'斯凯莱德大学(Strathclyde)',
u'城市大学(City)',
u'基尔大学(Keele)',
u'考文垂大学(Coventry)',
u'布鲁内尔大学(Brunel)',
u'斯旺西大学(Swansea)',
u'伦敦大学金史密斯学院(Goldsmiths)',
u'邓迪大学(Dundee)',
u'牛津布鲁克斯大学(Oxford Brookes)',
u'斯特灵大学(Stirling)',
u'罗伯特戈登大学（Robert Gordon）',
u'切斯特大学(Chester)',
u'伯恩茅斯艺术学院(Arts Bournemouth)',
u'朴茨茅斯大学(Portsmouth)',
u'班戈大学(Bangor)',
u'林肯大学(Lincoln)',
u'温彻斯特大学(Winchester)',
u'北安普顿大学(Northampton)',
u'西英格兰布里斯托大学(Bristol west of England)',
u'诺丁汉特伦特大学(Nottingham Trent)',
u'诺森比亚大学(Northumbria) ',
u'诺丁汉特伦特大学(Nottingham Trent)',
u'诺森比亚大学(Northumbria) ',
u'赫尔大学(Hull)',
u'约克圣约翰大学(York St John)',
u'哈勃亚当斯大学(Harper Adams)',
u'哈德斯菲尔德大学(Huddersfield)',
u'伯恩茅斯大学(Bournemouth)',
u'奇切斯特大学(Chichester)',
u'边山大学(Edge Hill)',
u'巴斯泉大学(Bath Spa)',
u'玛格丽特皇后学院(Queen Margaret)',
u'圣马克和圣约翰大学(St Mark and St John)',
u'普利茅斯大学(Plymouth)',
u'阿尔斯特大学(Ulster)',
u'布莱顿大学(Brighton)',
u'伦敦艺术大学(Arts-London)',
u'谢菲尔德哈莱姆大学(Sheffield Hallam)',
u'法茅斯大学 (Falmouth)',
u'罗汉普顿大学(Roehampton)',
u'格拉斯哥喀里多尼亚大学(Glasgow Caledonian)',
u'阿伯里斯特威斯大学(Aberystwyth)',
u'利物浦约翰摩尔斯大学(Liverpool John Moores)',
u'布拉德福德大学(Bradford)',
u'德比大学(Derby)',
u'德蒙福特大学(De Montfort)',
u'卡迪夫城市大学(Cardiff Metropolitan)',
u'中央兰开夏大学(Central Lancashire)',
u'曼彻斯特城市大学(Manchester Metropolitan)',
u'坎特伯里基督教会大学(Canterbury Christ Church)',
u'格洛斯特郡大学(Gloucestershire)',
u'伯明翰城市大学(Birmingham City)',
u'格洛斯特郡大学(Gloucestershire)',
u'伯明翰城市大学(Birmingham City)',
u'提塞德大学(Teesside)',
u'密德萨斯大学(Middlesex University)',
u'哥比亚大学(Cumbria)',
u'赫特福德郡大学(Hertfordshire)',
u'桑德兰大学(Sunderland)',
u'索尔福德大学(Salford)',
u'创作艺术大学学院(Creative Arts) ',
u'龙比亚大学(Edinburgh Napier)',
u'格林尼治大学(Greenwich)',
u'伍斯特大学(Worcester)',
u'利兹都市大学(Leeds Metropolitan)',
u'利兹三一大学(Leeds Trinity)',
u'阿伯泰邓迪大学(Abertay Dundee)',
u'威斯敏斯特大学(Westminster)',
u'格罗斯泰特主教大学(Bishop Grosseteste)',
u'斯坦福郡大学(Staffordshire)',
u'格林多大学(Glyndwr)',
u'安格利亚鲁斯金大学(Anglia Ruskin)',
u'金斯顿大学(Kingston)',
u'西伦敦大学(West London)',
u'新白金汉大学(Buckinghamshire New)',
u'南安普顿索伦特大学(Southampton Solent)',
u'贝德福德郡大学(Bedfordshire)',
u'高地和群岛大学(Highlands and Islands)',
u'西苏格兰大学(West of Scotland)',
u'南岸大学(South Bank)',
u'波尔顿大学(Bolton)',
u'东伦敦大学(East London)',
u'伦敦都市大学(London Metropolita']

for org in orgs:
	orgS = Organization(org, "")
	db.session.add(orgS)
db.session.commit()

kes = [u'SOA Motivation and Approach',
u'SOA Governance Motivation and Approach',
u'SOA Basic Concepts',
u'XML',
u'Web Service Basic',
u'BPEL', 
u'WBM',
u'WID',
u'SCA',
u'SDO',
u'WPS',
u'ESB',
u'Connectivity',
u'SOA Governance Basic Concepts',
u'Business Process Analysis and Practices',
u'Road to SOA Enterprise Application Integration']

stds = [u'SOAP',
u'WSDL',
u'UDDI',
u'RDF',
u'RDFS',
u'OWL',
u'BPEL4WS',
u'WSCI',
u'WS-C',
u'ebXML',
u'FIPA',
u'OWL-S']

tools = [u'WebSphere Application Server',
u'WebSphere MQ',
u'WebSphere Portal',
u'WebSphere Enterprise Service Bus',
u'WebSphere Message Broker',
u'WebSphere Business Monitor',
u'WebSphere Business Modeler',
u'WebSphere Adapters',
u'WebSphere Commerce',
u'WebSphere Integration Developer',
u'WebSphere Studio',
u'WebSphere Developer for z/Series',
u'WebSphere Process Server']

for std in stds:
	stdS = StandardAndSpe(std, "")
	db.session.add(stdS)
db.session.commit()


for tool in tools:
	toolS = Tool(tool, "")
	db.session.add(toolS)
db.session.commit()


for ke in kes:
	know = KnowledgeElement(ke, 0, 0, "")
	db.session.add(know)
db.session.commit()


user = User('admin', '', 'soasocadmin')
db.session.add(user)
db.session.commit()
user = User.query.filter_by(id = 1).first()
user.role = 2
db.session.commit()

